name: aiva-cli
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
      - google-generativeai>=0.3.0
      - pillow>=9.0.0
      - typer>=0.9.0
      - rich>=13.0.0
      - python-dotenv>=1.0.0
      - pydantic>=2.0.0
      - requests>=2.28.0
      - pathlib2>=2.3.0
